spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/test
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: '8081'
  
  
ems:
  messages:
    employee-not-found : "Employee Not Found With Id : %s "
    employee-deletion-succeeded: "Employee Deleted Successfully With Id : "
      
  
  
